from logging import exception
from django.conf import settings
from django.shortcuts import redirect, render
from django.db.utils import IntegrityError
from App.models import User, Recording
from django.contrib.auth import logout as logout_user
from django.core.mail import send_mail, EmailMessage
from django.template.loader import render_to_string, get_template
from django.utils.translation import gettext as _
import random

# Render the "user" page,
# Parameters include error messages when user tries to change info
def render_user_change(Request,
                ChangeFailed=False,
                Inconsistency=False,
                UsedName=False) :
    Context          = {}
    Context["ChangeFailed"] = ChangeFailed
    Context["Inconsistency"] = Inconsistency
    Context["UsedName"] = UsedName
    return render(Request, 'user_change.html', Context)

def render_user_info(Request, Users) :
    Context                     = {}
    Context["UserList"]         = []
    for user in Users :
        OwnRecordings = Recording.objects.filter(UploadUser=user)
        Context["UserList"].append({"user": user, "recordings": OwnRecordings})
    return render(Request, 'user.html', Context)

# Process a submitted change-user-info form
def process_user_change_form(Request, Avatar, UserName, Email, Password, Password2, Introduction="Empty") :

    OldUserName = Request.user.username
    print('changing', OldUserName, 'to', UserName, Email, Password, Password2, Introduction)

    CurUser = User.objects.get(username=OldUserName)

    if Password and Password2 : # change password
        if Password != Password2 : # different password
            return {"change_failed": True, "inconsistent_password": True, "conflict_username": False}
        else :
            CurUser.set_password(Password)
    
    print(Avatar)

    if Avatar :
        CurUser.Avatar = Avatar
    
    if UserName != OldUserName : # change user name
        CurUser.username=UserName

    if Introduction :
        CurUser.Introduction = Introduction
    
    if Email :
        CurUser.email = Email

    try:
        CurUser.save()
    except IntegrityError as e: # Possibly conflicting username
        return {"change_failed": True, "inconsistent_password": False, "conflict_username": True}

    CurUser.save()
    Request.user = CurUser
    
    return {"change_failed": False, "inconsistent_password": False, "conflict_username": False}

def process_user_delete(Request) :

    Request.user.delete()

# Send a link to the user's email address to verify
def send_verification_email(CurUser: User):
    CurUser.VerificationCode = ''.join([random.choice('zyxwvutsrqponmlkjihgfedcba') for i in range(16)])
    CurUser.save()

    content = {
        "user": CurUser.get_username(),
        "site": settings.SITE_URL,
        "url": "{0}/user/{1}/verify/{2}/".format(settings.SITE_URL,
            CurUser.get_username(),
            CurUser.VerificationCode
        )
    }

    message = get_template('email.html').render(content)
    Msg = EmailMessage(
        'Email Verification',
        message,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=[CurUser.get_email()],
        reply_to=[settings.DEFAULT_FROM_EMAIL],
    )
    Msg.content_subtype ="html"# Main content is now text/html
    Msg.send()

# If the user clicks the verification link, verify
def process_verification(Request, UserName, Code) :

    try :
        CurUser = User.objects.get(username=UserName)
    except :
        print("User not found in process_verification")
        return {"verification_failed": True, "reason": "User not found!"}

    print(CurUser.VerificationCode, Code)
    
    if CurUser.VerificationCode == Code :   # VerificationCode is pre-generated by send_verification_email()
        CurUser.EmailVerified = True
        CurUser.save()
        return {"verification_failed": False, "reason": _("Congratulations! You can now access the full content of this website.")}
    else :
        return {"verification_failed": True, "reason": _("Verification code incorrect!")}

# A decorator, redirects to index if email not verified
def verification_required(func) :

    def decorated(*args, **kwargs):

        User = args[0].user
        if User.EmailVerified :
            return func(*args, **kwargs)
        else :
            return redirect('/')
    
    return decorated