# Generated by Django 4.0.6 on 2022-08-01 18:05

import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('Introduction', models.CharField(default='Empty', max_length=65535)),
                ('Country', models.CharField(default='Unknown', max_length=255)),
                ('Birthday', models.DateField(default=datetime.date(1900, 1, 1))),
                ('Deathday', models.DateField(default=datetime.date(1900, 1, 1))),
                ('Alive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Introduction', models.CharField(default='This person is mysterious', max_length=65535)),
                ('EmailVerified', models.BooleanField(default=False)),
                ('VerificationCode', models.CharField(default='', max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='Mysterious Recording', max_length=255)),
                ('File', models.FileField(upload_to='Recordings')),
                ('UploadUserName', models.CharField(default='Anonymous', max_length=255)),
                ('Description', models.CharField(default='Empty', max_length=65535)),
                ('UploadTime', models.DateTimeField(auto_now=True)),
                ('LastEditTime', models.DateTimeField(auto_now=True)),
                ('Views', models.IntegerField(default=0)),
                ('Composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recordings', to='App.composer')),
                ('UploadUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recordings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
