# Generated by Django 4.0.6 on 2022-08-06 17:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='Avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatar/matthew.png', upload_to='avatar', verbose_name='头像'),
        ),
    ]
